apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
  labels:
    app: svc1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: bcap/caller
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 200Mi

        # necessary, check notes at
        # https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  type: LoadBalancer
  selector:
    app: svc1
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2
  labels:
    app: svc2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
      - name: svc2
        image: bcap/caller
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 200Mi

        # necessary, check notes at
        # https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: svc2
spec:
  type: LoadBalancer
  selector:
    app: svc2
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc3
  labels:
    app: svc3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc3
  template:
    metadata:
      labels:
        app: svc3
    spec:
      containers:
      - name: svc3
        image: bcap/caller
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 200Mi

        # necessary, check notes at
        # https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: svc3
spec:
  type: LoadBalancer
  selector:
    app: svc3
  ports:
  - port: 80
    targetPort: 8080

